## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('mobitrade', ['internet-stack', 'contrib'])
    module.includes = '.'
    module.source = [
        'mobitrade_msg_header.cc',
        'mobitrade_protocol.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'mobitrade'
    headers.source = [
        'mobitrade_msg_header.h',
        'mobitrade_protocol.h',
        ]

